name: test
on:
  push:
    branches:
      - dev
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: install-node
        run: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - name: install-dependencies
        run: npm install